export const ROUTES = {
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_OTP: '/verify-otp',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/',
  PRODUCTS: '/products',
  CATEGORIES: '/categories',
  REORDER: '/reorder-rules',
  RECEIPTS: '/receipts',
  DELIVERIES: '/deliveries',
  TRANSFERS: '/transfers',
  ADJUSTMENTS: '/adjustments',
  MOVE_HISTORY: '/move-history',
  WAREHOUSE: '/warehouse',
  ALERTS: '/alerts',
  PROFILE: '/profile',
  SETTINGS: '/settings',
  FORBIDDEN: '/forbidden',
  UNAUTHORIZED: '/unauthorized',
  SERVER_ERROR: '/server-error',
};
