export const DEMO_PASSWORD = 'StockSense#2026';

export const USERS = [
  ['Asha Mehta', 'manager@stocksense.demo', 'inventory_manager', 'active'],
  ['Rohan Desai', 'staff@stocksense.demo', 'warehouse_staff', 'active'],
  ['Neel Shah', 'neel.shah@stocksense.demo', 'inventory_manager', 'active'],
  ['Priya Nair', 'priya.nair@stocksense.demo', 'warehouse_staff', 'active'],
  ['Kabir Joshi', 'kabir.joshi@stocksense.demo', 'warehouse_staff', 'active'],
  ['Meera Iyer', 'meera.iyer@stocksense.demo', 'warehouse_staff', 'active'],
  ['Arjun Patel', 'arjun.patel@stocksense.demo', 'inventory_manager', 'active'],
  ['Lila Kapoor', 'unverified@stocksense.demo', 'warehouse_staff', 'unverified'],
];

export const CATEGORIES = [
  ['Fasteners', 'Bolts, nuts, washers, and anchors used across assembly lines.'],
  ['Raw Metals', 'Bars, sheets, and coils held for fabrication.'],
  ['Packaging', 'Cartons, film, and labels used to ship finished goods.'],
  ['Electrical', 'Cable, switches, and components for plant maintenance.'],
  ['Safety Equipment', 'Protective gear issued to warehouse and production teams.'],
  ['Lubricants', 'Oils and greases for machinery upkeep.'],
  ['Hand Tools', 'Tools kept in stores for maintenance crews.'],
  ['Spare Parts', 'Replacement parts for conveyors, pumps, and motors.'],
  ['Chemicals', 'Cleaning and treatment chemicals stored under control.'],
  ['Finished Goods', 'Completed items ready for customer delivery.'],
  ['Textiles', 'Fabric, webbing, and stitching consumables.'],
  ['Office Supplies', 'Stores used by the warehouse office.'],
];

export const WAREHOUSES = [
  ['Main Distribution Center', 'WH-MDC', 'Plot 12, Sarkhej-Bavla Highway, Ahmedabad', '+91 79 4000 1101'],
  ['West Regional Hub', 'WH-WRH', 'Kalavad Road, Rajkot', '+91 281 400 2202'],
  ['Production Store', 'WH-PRD', 'Pandesara GIDC, Surat', '+91 261 400 3303'],
  ['Dispatch Depot', 'WH-DSP', 'Makarpura, Vadodara', '+91 265 400 4404'],
];

export const LOCATION_TEMPLATES = [
  ['Receiving Bay', 'RCV'],
  ['Rack A', 'RKA'],
  ['Rack B', 'RKB'],
  ['Rack C', 'RKC'],
  ['Quarantine', 'QTN'],
  ['Dispatch Floor', 'DSP'],
];

export const SUPPLIERS = [
  'Metro Steel Traders', 'Gujarat Fastener Co.', 'Sahara Packaging', 'Western Lubricants',
  'Narmada Electricals', 'Patel Safety House', 'Coastal Textiles', 'Orbit Tooling',
];

export const CUSTOMERS = [
  'Aarav Engineering', 'Bluepeak Retail', 'Shakti Fabricators', 'Northwind Plants',
  'Helio Contractors', 'Saffron Hospitals', 'Delta Warehousing', 'Kaveri Mills',
];

export const REASONS = [
  'Cycle count variance', 'Damaged packaging written off', 'Found during recount',
  'Supplier short-shipment correction', 'Spillage during handling',
];

// name, sku, category, unit, reorder level
export const PRODUCTS = [
  ['Hex Bolt M6 x 20', 'FST-HB-M6', 'Fasteners', 'PCS', 400],
  ['Hex Bolt M8 x 30', 'FST-HB-M8', 'Fasteners', 'PCS', 350],
  ['Hex Nut M8', 'FST-HN-M8', 'Fasteners', 'PCS', 500],
  ['Spring Washer M8', 'FST-SW-M8', 'Fasteners', 'PCS', 300],
  ['Anchor Bolt M12', 'FST-AB-M12', 'Fasteners', 'PCS', 120],
  ['Self-tapping Screw 4x25', 'FST-SS-425', 'Fasteners', 'PCS', 800],
  ['Threaded Rod M10', 'FST-TR-M10', 'Fasteners', 'M', 40],
  ['Mild Steel Round Bar 12mm', 'MET-RB-12', 'Raw Metals', 'KG', 200],
  ['Mild Steel Round Bar 20mm', 'MET-RB-20', 'Raw Metals', 'KG', 180],
  ['HR Sheet 2mm', 'MET-HR-2', 'Raw Metals', 'KG', 250],
  ['CR Sheet 1.2mm', 'MET-CR-12', 'Raw Metals', 'KG', 160],
  ['Aluminium Flat 25mm', 'MET-AL-25', 'Raw Metals', 'KG', 80],
  ['Copper Strip 10mm', 'MET-CU-10', 'Raw Metals', 'KG', 40],
  ['GI Coil 0.5mm', 'MET-GI-05', 'Raw Metals', 'KG', 300],
  ['Corrugated Box 12x10', 'PKG-BX-1210', 'Packaging', 'PCS', 200],
  ['Corrugated Box 18x14', 'PKG-BX-1814', 'Packaging', 'PCS', 150],
  ['Stretch Film 23 mic', 'PKG-SF-23', 'Packaging', 'ROLL', 30],
  ['Bubble Roll 10m', 'PKG-BB-10', 'Packaging', 'ROLL', 20],
  ['Packing Tape 48mm', 'PKG-TP-48', 'Packaging', 'ROLL', 60],
  ['Shipping Label Roll', 'PKG-LB-01', 'Packaging', 'ROLL', 25],
  ['Pallet Corner Guard', 'PKG-CG-01', 'Packaging', 'PCS', 100],
  ['Copper Cable 1.5 sqmm', 'ELC-CB-15', 'Electrical', 'M', 200],
  ['Copper Cable 2.5 sqmm', 'ELC-CB-25', 'Electrical', 'M', 150],
  ['MCB 16A Single Pole', 'ELC-MC-16', 'Electrical', 'PCS', 40],
  ['LED Batten 20W', 'ELC-LD-20', 'Electrical', 'PCS', 25],
  ['Limit Switch', 'ELC-LS-01', 'Electrical', 'PCS', 15],
  ['Panel Indicator Lamp', 'ELC-IN-01', 'Electrical', 'PCS', 30],
  ['Cable Tie 200mm', 'ELC-CT-200', 'Electrical', 'PCS', 500],
  ['Safety Helmet Yellow', 'SAF-HM-YL', 'Safety Equipment', 'PCS', 40],
  ['Safety Goggles', 'SAF-GG-01', 'Safety Equipment', 'PCS', 50],
  ['Nitrile Gloves L', 'SAF-GL-L', 'Safety Equipment', 'BOX', 30],
  ['Ear Plug Corded', 'SAF-EP-01', 'Safety Equipment', 'BOX', 20],
  ['High-visibility Vest', 'SAF-VS-01', 'Safety Equipment', 'PCS', 35],
  ['Safety Shoes Size 8', 'SAF-SH-08', 'Safety Equipment', 'PCS', 12],
  ['First Aid Refill Kit', 'SAF-FA-01', 'Safety Equipment', 'SET', 8],
  ['Hydraulic Oil ISO 68', 'LUB-HO-68', 'Lubricants', 'L', 60],
  ['Gear Oil EP 90', 'LUB-GO-90', 'Lubricants', 'L', 40],
  ['Lithium Grease EP2', 'LUB-GR-EP2', 'Lubricants', 'KG', 25],
  ['Cutting Oil', 'LUB-CO-01', 'Lubricants', 'L', 30],
  ['Chain Lubricant Spray', 'LUB-CS-01', 'Lubricants', 'PCS', 20],
  ['WD Penetrating Oil', 'LUB-WD-01', 'Lubricants', 'PCS', 24],
  ['Combination Spanner 13mm', 'TOL-SP-13', 'Hand Tools', 'PCS', 10],
  ['Adjustable Wrench 10in', 'TOL-AW-10', 'Hand Tools', 'PCS', 8],
  ['Ball Pein Hammer 500g', 'TOL-HM-500', 'Hand Tools', 'PCS', 6],
  ['Measuring Tape 5m', 'TOL-MT-5', 'Hand Tools', 'PCS', 15],
  ['Torque Wrench 1/2', 'TOL-TW-12', 'Hand Tools', 'PCS', 4],
  ['Needle File Set', 'TOL-NF-01', 'Hand Tools', 'SET', 6],
  ['Conveyor Belt 500mm', 'SPR-CB-500', 'Spare Parts', 'M', 20],
  ['Bearing 6204 ZZ', 'SPR-BR-6204', 'Spare Parts', 'PCS', 30],
  ['V-Belt A42', 'SPR-VB-A42', 'Spare Parts', 'PCS', 12],
  ['Pump Seal Kit', 'SPR-PS-01', 'Spare Parts', 'SET', 6],
  ['Proximity Sensor M18', 'SPR-PX-M18', 'Spare Parts', 'PCS', 10],
  ['Gearbox Coupling', 'SPR-GC-01', 'Spare Parts', 'PCS', 4],
  ['Filter Element 10 mic', 'SPR-FE-10', 'Spare Parts', 'PCS', 18],
  ['Degreaser Concentrate', 'CHM-DG-01', 'Chemicals', 'L', 40],
  ['Floor Cleaner', 'CHM-FL-01', 'Chemicals', 'L', 30],
  ['Rust Remover', 'CHM-RR-01', 'Chemicals', 'L', 15],
  ['Isopropyl Alcohol 5L', 'CHM-IPA-5', 'Chemicals', 'PCS', 10],
  ['Hand Soap Cartridge', 'CHM-HS-01', 'Chemicals', 'PCS', 20],
  ['Welded Frame Type A', 'FIN-FR-A', 'Finished Goods', 'PCS', 15],
  ['Welded Frame Type B', 'FIN-FR-B', 'Finished Goods', 'PCS', 12],
  ['Storage Rack Bay', 'FIN-RK-01', 'Finished Goods', 'PCS', 8],
  ['Tool Cabinet 6 Drawer', 'FIN-TC-6', 'Finished Goods', 'PCS', 5],
  ['Work Table 1500mm', 'FIN-WT-15', 'Finished Goods', 'PCS', 6],
  ['Pallet Truck 2.5T', 'FIN-PT-25', 'Finished Goods', 'PCS', 3],
  ['Cotton Webbing 25mm', 'TEX-WB-25', 'Textiles', 'M', 100],
  ['Canvas Roll 1.5m', 'TEX-CV-15', 'Textiles', 'M', 40],
  ['Polyester Thread Cone', 'TEX-TH-01', 'Textiles', 'PCS', 50],
  ['Felt Pad Sheet', 'TEX-FP-01', 'Textiles', 'PCS', 30],
  ['Elastic Cord 6mm', 'TEX-EC-6', 'Textiles', 'M', 80],
  ['Copy Paper A4', 'OFS-PP-A4', 'Office Supplies', 'BOX', 10],
  ['Permanent Marker', 'OFS-MK-01', 'Office Supplies', 'BOX', 8],
  ['Barcode Label 50x25', 'OFS-BC-50', 'Office Supplies', 'ROLL', 12],
  ['Document Folder', 'OFS-FD-01', 'Office Supplies', 'PCS', 40],
  ['Ballpoint Pen Blue', 'OFS-PN-BL', 'Office Supplies', 'BOX', 6],
  ['Stapler Heavy Duty', 'OFS-ST-01', 'Office Supplies', 'PCS', 4],
  ['Nylon Lock Nut M10', 'FST-LN-M10', 'Fasteners', 'PCS', 250],
  ['Flat Washer M10', 'FST-FW-M10', 'Fasteners', 'PCS', 300],
  ['Stainless Sheet 1mm', 'MET-SS-1', 'Raw Metals', 'KG', 90],
  ['Cable Gland PG16', 'ELC-CG-16', 'Electrical', 'PCS', 40],
];
